name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build ChatGPT.UI.Desktop
      run: dotnet build src/ChatGPT.UI.Desktop/ChatGPT.UI.Desktop.csproj --configuration Release
  build_windows_browser:
    name: Build Windows Browser
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build ChatGPT.UI.Browser
      run: dotnet build src/ChatGPT.UI.Browser/ChatGPT.UI.Browser.csproj --configuration Release
  build_windows_android:
    name: Build Windows Android
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install android
    - name: Build ChatGPT.UI.Android
      run: dotnet build src/ChatGPT.UI.Android/ChatGPT.UI.Android.csproj --configuration Release
  build_windows_ios:
    name: Build Windows iOS
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install iOS
    - name: Build ChatGPT.UI.iOS
      run: dotnet build src/ChatGPT.UI.iOS/ChatGPT.UI.iOS.csproj --configuration Release
  build_linux:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental android
    - name: Build ChatGPT.UI.Desktop
      run: dotnet build src/ChatGPT.UI.Desktop/ChatGPT.UI.Desktop.csproj --configuration Release
    - name: Build ChatGPT.UI.Android
      run: dotnet build src/ChatGPT.UI.Android/ChatGPT.UI.Android.csproj --configuration Release
    - name: Build ChatGPT.UI.Browser
      run: dotnet build src/ChatGPT.UI.Browser/ChatGPT.UI.Browser.csproj --configuration Release
  build_macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental android ios
    - name: Build ChatGPT.UI.Desktop
      run: dotnet build src/ChatGPT.UI.Desktop/ChatGPT.UI.Desktop.csproj --configuration Release
    - name: Build ChatGPT.UI.iOS
      run: dotnet build src/ChatGPT.UI.iOS/ChatGPT.UI.iOS.csproj --configuration Release
    - name: Build ChatGPT.UI.Browser
      run: dotnet build src/ChatGPT.UI.Browser/ChatGPT.UI.Browser.csproj --configuration Release
